### ISSUE TITLE
Cannot open the SeS

### ISSUE THREAD

**Issue by Badiue** [ruuvi/ruuvi.firmware.c#10]
when im try to open the ses file it say crash . im using Seeger Embedded Studio for ARM v4.12

**Comment by ojousima** [comment]
Could you give more details?
 * Which tag you're on? 
 * Have you downloaded the Nordic SDK?
 * Have you updated git modules?
 * Which OS you're on?
 * Can you give the crash report?

**Comment by Badiue** [comment]
im using ruuvitag
im downloaded  nRF5_SDK_15.2.0_9412b96
im alredy update git module
im using ubuntu 18.04
![Screenshot from 2019-03-29 15-31-29](https://user-images.githubusercontent.com/48235931/55216540-fd6d7a00-5237-11e9-8b07-3cffab2226e7.png)

**Comment by ojousima** [comment]
I can open the project on 4.12 on MacOSX and Windows, so this might have something to do with the linux version of SES. I don't have a Linux installation I could use to check the issue. 

Can you open the Nordic SDK examples with your SES installation?

**Comment by Badiue** [comment]
yes,i can open Nordic SDK,im also have try using ruuvitag_fw and it work for this.
thank for the info,i will try using windows.

**Comment by ojousima** [comment]
@Badiue Was the issue resolved with Windows?

**Comment by ojousima** [comment]
Closing as stale
