### ISSUE TITLE
3.29.X: Poor GATT connection might lead to watchdog reboot

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#163]
On a poor connection, it takes over 120 seconds to transfer logs. This will lead to watchdog triggering and reboot, with associated loss of logged data. Applications should always disconnect at 60 seconds tx is ongoing, and firmware could kick the connection at 90 seconds or so.

**Comment by ojousima** [comment]
For now, this will be the responsibility of the reader. If log transfer takes over 60 seconds, reader should disconnect.

**Comment by ojousima** [comment]
Fixed, tag kicks connection before watchdog timer triggers.

**Comment by DG12** [comment]
Why not add a occasional dog feed ?

**Comment by ojousima** [comment]
If there is a bug which causes log processing to loop forever, watchdog needs to trigger.

**Comment by DG12** [comment]
Perhaps a better solution to this particular known case (which is not really a bug) is to incorporate a timeout in the GATT transmission. The reader who doesn't even know that there is a problem until it's too late.  The reader can move to a more "friendly" (closer) location and try again or at a different time when there is less interference.

 The wdog reset will cause all historical data to be erased. 

Relying on the reader, which might not be a Ruuvi app but written by the user, doesn't sound like a good idea.

**Comment by ojousima** [comment]
>> Perhaps a better solution to this particular known case (which is not really a bug) is to incorporate a timeout in the GATT transmission. The reader who doesn't even know that there is a problem until it's too late. The reader can move to a more "friendly" (closer) location and try again or at a different time when there is less interference.
The wdog reset will cause all historical data to be erased.
Relying on the reader, which might not be a Ruuvi app but written by the user, doesn't sound like a good idea.

> Fixed, tag kicks connection before watchdog timer triggers.

Already done
