### ISSUE TITLE
3.29.1: Logs are erased on read timeout

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#175]
If log read takes over 120 seconds, watchdog resets the tag which leads to RTC loss, which leads to losing logs

**Comment by ojousima** [comment]
A quick fix is to increment log read interval to 5 minutes

**Comment by DG12** [comment]
See corresponding station issue https://github.com/ruuvi/com.ruuvi.station.ios/issues/156
