### ISSUE TITLE
Tests: Add a GATT test for log read speed

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#178]
Tag should run debug variant for at least 3 hours and data should be read with nRF devkit, possibly with the same throughput FW as in system tests

**Comment by DG12** [comment]
I am currently testing with NO delays by the caller since only ri_log knows destination speed and status of previous messages. With RTT checking  delay proportional to number of characters in message is the way to go.

**Comment by ojousima** [comment]
Clarifying, test for GATT log read speed. Unrelated to RTT, related to system tests

**Comment by ojousima** [comment]
Added in 3.29.X
