### ISSUE TITLE
3.29.1  remove ifndef s for setting which are not settable - question

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#180]
In files like src/application_config/app_config.h
is it better to **not** have ifdef commands for VARIABLES that are only permitted with values defined in app_config.h.
This would cause a **desirable** compilation error if a previous source file attempted to override a setting with an  illegal value.
For example:
```
#ifndef APP_SENSOR_SHTCX_RESOLUTION
#   define APP_SENSOR_SHTCX_RESOLUTION RD_SENSOR_CFG_DEFAULT 
// Only default resolution supported.
#endif
```

**Comment by ojousima** [comment]
That's a good point, presenting users with options that can only result in error isn't a good practice. Pull requests are welcome and I'll keep it in mind when working on the configuration.
