### ISSUE TITLE
3.29.3 movement counter updated by 2 on every other movement - defect; priority:L 

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#182]
Running test version with j-link and JLinkRTTClient
Moving RuuviTag slightly. Log report movement but movement counter is not incremented.
Move slightly again, log reports movement and movement counter is incremented by 2 !

**Comment by ojousima** [comment]
That's curious, has this been checked against measurement sequence counter of advertisements? Thanks for the report, I'll check the encoding and counter logic anyway and try to repeat

**Comment by DG12** [comment]
This does not occur in 2.5.9

**Comment by DG12** [comment]
Consequence of this is that a single movement  is not reported until another movemet occurs which might be a long time later.

**Comment by ojousima** [comment]
I can repeat on a devkit

**Comment by ojousima** [comment]
Fixed in #185, root cause was that tests didn't verify params going to encoding. Fix will be included in next release.
