### ISSUE TITLE
app_log.c/store_block has one parameter  but does not use it. - 

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#192]
Apparently the gcc warning "parameter not used" is disabled. Since all calls to store_block currently use m_log_input_block anyway this works but "smells?".
```
static rd_status_t store_block (const app_log_record_t * const record)
```
...
```
  err_code |= rt_flash_store (APP_FLASH_LOG_FILE,
                                    (APP_FLASH_LOG_DATA_RECORD_PREFIX << 8U) + record_idx,
                                    &m_log_input_block, sizeof (m_log_input_block));
```
app_log_process :err_code |= store_block (&m_log_input_block);

app_log_config_set :    store_block (&m_log_input_block); 
// return code not checked apparently gcc didn't catch that.

store_block prototype not in app_log.h

It seems that calling rt_flash_gc_run  with every store_block will cause gc to take the available "slot" of the most recently erased record and rewrite all following records "down one slot". With the initializing of record_idx =0, it seems that rt_flash_free will always free the first record.

**Comment by ojousima** [comment]
> store_block prototype not in app_log.h

This is internal function, as indicated by `static`

> app_log_config_set : store_block (&m_log_input_block);
> // return code not checked apparently gcc didn't catch that.

The point is just to flush data stored with old config to flash, but you're right that `(void)store_block (&m_log_input_block);` would make ignoring the return code explicit. A pull request is welcome on that.
