### ISSUE TITLE
3.30.0: Test binaries

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#199]
Test process is described at https://docs.ruuvi.com/ruuvi-firmware/3.x/releases, 

The 3.x and 3.29 checklists need to be compared to one another, and any updates from 3.29 versions need to be moved under 3.x checklist. 

Firmware needs to be checked on as many board variants as possible.

**Comment by niksiboxi** [comment]
Tested with RuuviTag B+ & RuuviTag B+ (SHTCX)

**Comment by niksiboxi** [comment]
@ojousima Will you test the RuuviTag Basic?

**Comment by ojousima** [comment]
@niksiboxi yes, we'll also need to redo the power measurements on RC7

**Comment by niksiboxi** [comment]
@ojousima  Ok, will do the tests asap.

**Comment by niksiboxi** [comment]
Added 3.30-RC7 power measurements.

**Comment by niksiboxi** [comment]
@ojousima Is there any tests to be done still missing?

**Comment by DG12** [comment]
Is this expected?

"nRF5TMP": {
"init":"pass",
"modes":"pass",
"configuration":"**fail"**,
"interrupts":"skipped",
"data":{
"timestamp_ms": "ld",
"temperature_c": "22.75"
}

**Comment by ojousima** [comment]
>Is this expected?
>
>"nRF5TMP": {
>"init":"pass",
>"modes":"pass",
>"configuration":"fail",
>"interrupts":"skipped",
>"data":{
>"timestamp_ms": "ld",
>"temperature_c": "22.75"
>}

@niksiboxi is working on it
