### ISSUE TITLE
Change names referring to stored data from log  - 3.30.0 - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#202]
Both the names of functions and modules referring to the "stored in flash" history should be changed from log (which refers to the diagnostic output sent to Segger Real Time Transfer) to something unique like "his"

**Comment by niksiboxi** [comment]
@DG12 So, you would like to replace e.g. `LOG: Sample received` with `HIS: Sample received`? 

And what does `his` stands for it this context?

**Comment by ojousima** [comment]
Closing as stale
