### ISSUE TITLE
Transmit  log(history) in advertisement format - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#210]
I realize that the long term plan is to support many different sensors (some even for existing measurements)
It seems that since current systems to receive data (particularly ruuvistation and ruuvistation IOS) already have code to process the format rawV2(05) it would be worth the level of effort to transmit the log in advertisement format.
Along with actual storing the data in the ruuvitag in advertise format (see issue #99) would actually reduce the code size in the ruuvitag.

I would be willing to contribute toward this effort.

**Comment by DG12** [comment]
I realize that the long term plan is to support many different sensors (some even for existing measurements)
It seems that since current systems to receive data (particularly ruuvistation and ruuvistation IOS) already have code to process the format rawV2(05) it would be worth the level of effort to transmit the log in advertisement format. 
Along with actual storing the data in the ruuvitag in advertise format would (see issue #99) would actually reduce the code size in the ruuvitag.

I would be willing to contribute toward this effort.

**Comment by ojousima** [comment]
There certainly would be benefits in writing code for the one existing special case, and if there is some use case where extra space in flash is critical we might make a branch which has the more compact form. However, for all existing gateway implementations the current memory range is enough, so adding complexity by adding this special case in the mainline firmware is not beneficial.
