### ISSUE TITLE
3.29.3: repeats advertisements really fast in 90 second cycle in some case

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#229]

**Comment by ojousima** [comment]
![image](https://user-images.githubusercontent.com/2360368/110968043-b9f67280-835f-11eb-8f4f-ad0d7e03dc84.png)
Not exactly 90 sec. 19:11:27 , 19:13:03, 19:14:40, 19:16:16

**Comment by andreevdenis** [comment]
Duration is about 5 seconds. Rebooting sensor didn't help

**Comment by DG12** [comment]
@ojousima What did you use to generate that display?

**Comment by ojousima** [comment]
@ojousima What did you use to generate that display?

@andreevdenis console logs

**Comment by DG12** [comment]
> What did you use to generate that display?
> 
> @andreevdenis console logs
Can you please provide a little more detail.

**Comment by andreevdenis** [comment]
@DG12 This screen is from Android Studio. I was doing https://github.com/ruuvi/com.ruuvi.station/issues/166 and put logging for cases when BT library should filter measurement from sensor. One of my sensors was acting wierd

**Comment by ojousima** [comment]
@niksiboxi please check if this can be repeated on 3.30 somehow

**Comment by niksiboxi** [comment]
@ojousima Could not reproduce.

Tested with GATT -> Read attributes/subscribed to NUS notifications.

**Comment by ojousima** [comment]
@niksiboxi This would be in advertisements, not in NUS notifications

**Comment by niksiboxi** [comment]
@ojousima Could not reproduce -> Tested advertisement.
