### ISSUE TITLE
Generalize measurement history data transmission with header - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#236]
The addition of a header record to the synchronization/download stream would permit differing sensor measurements to be downloaded and graphed.

Utilizing the current transmission stream, simply adding a header including the text of the  text of the Y-axis label, valid min and max.
For example for the current data stream
'°C','-40','85', '%','0','100','hPa','500','1100'
This requires a one time, fairly simple, change to the ruuviStation apps.

This would allow for tuning the firmware to transmit the:
Z-axis value instead of the air pressure by changing  the header to:
'°C','-40','85', '%','0','100','Z','-1','1'

or
movement counter instead of the air pressure:
'°C','-40','85', '%','0','100','#','0','254'

or considering RuuviTag B8 with a CO sensor:
'°C','-40','85', '%','0','100','ppm','0','50'

An extension would be to include a legend for the Y-axis although this is currently not displayed.

**Comment by ojousima** [comment]
The firmware already has a header byte defining the type of data
