### ISSUE TITLE
Transmitting history data column wise allows more(or less) graphs - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#237]
Consider the history data is currently being transmitted row wise, that is:

```
> time1 : temperature1 : humidity1 : airPressure1
> time2 : temperature2 : humidity2 : airPressure2
> ...
> timeN : temperatureN : humidityN : airPressureN
```
This restricts ruuviStation apps to 3 graphs.

The data could to be transmitted column wise, that is:
```

> time1 : temperature1 
> time2 : temperature2 
>   ...
> timeN : temperatureN
> Humidity1
> Humidity2
>   ...
> HumidityN
> airpressure1
> airpressure2
>   ...
> airpressureN
> Z-axis1
> Z-axis2
> ...
> Z-axisN

```
This would allow as few as one graph(sensor) or as many as the user configures the firmware for!

No this one is not easy.

Does the  transmission have integrity to prevent dropped blocks?
If the transmission does not have the integrity to prevent dropped blocks then a  more data(time) intensive method would include the times with all sensor columns.

**Comment by ojousima** [comment]
The data is already transmitted in the format `header (type); time; data`.

> Does the transmission have integrity to prevent dropped blocks? 

On BLE link layer, not on application layer.
