### ISSUE TITLE
linker script incorrectly blames tdata instead of data_load when over flowing flash

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#251]
The linker script for Segger Embedded Studio neglects to check data_load for over running storage_flash .

The following line, with a more meaningful error message,  should be added immediately after
`__data_load_end__ = (__data_load_start__ + SIZEOF (.data))
`
```
. = ASSERT (((__data_load_start__ == __data_load_end__) ||
(__data_load_end__ <=_storage_flash_start__), 
error:  static variable initialization  exceeds  FlashStorage assignment)

```
later checks
```
 . = ASSERT ((__tdata_load_end__ <= __storage_flash_start__),
 error: section .tdata overlaps absolute placed section .storage_flash)
```

blames tdata which is currently unused.

Where is this script??

The script for armgcc link should be checked for the same issue.

**Comment by ojousima** [comment]
SES generates the linker script from flash_placement.xml and project configuration. If there is an issue with the generated linker script issue should be opened on Segger side, we can only work around any SES issues here :)
