### ISSUE TITLE
Spikes in logged data

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#254]
Customer report, data was logged to RuuviTag FW 3.30.0+default.
It's uncertain if the problem is in sensor, logging, transmitting data, or receiving on Android. 
![image](https://user-images.githubusercontent.com/2360368/116097696-0cdb7d80-a6b3-11eb-9753-f0e630eb7939.png)

**Comment by DG12** [comment]
Can you get a download of the data?

**Comment by ojousima** [comment]
> Can you get a download of the data?

Not at this time

**Comment by ojousima** [comment]
Here's a similar dataset.
[Log 2021-04-28 12_20_23.txt](https://github.com/ruuvi/ruuvi.firmware.c/files/6393357/Log.2021-04-28.12_20_23.txt)

It seems that the issue is caused by:
1) Tag has open enclosure or is being handled
2) Something causes fast spike in humidity, e.g. user breathing on sensor
3) SHTC-tags do not have internal IIR filtering, which causes the humidity to spike

Next thing to decide is do we leave everything as is or filter the change somehow?

**Comment by DG12** [comment]
In order of desirability and implementation difficulty most desirable and most difficult listed first.

option 1: filter at the firmware level and include a runtime configurable filter(i.e. no compile #define) both to enable/disable filter and define the severity of the filter. This mitigates having any of the various receiving system, by various authors, having to implement a filter on a per Ruuvitag basis. Some use cases may not want to filter.

option 2:  filter at the firmware level with a compile time default based on the philosophy that the sensor has an inherent property that may need a variable correction.

option 3  filter at the firmware level philosophy that the sensor has an inherent property that always needs a fixed correction

option 4: let the firmware transmit what ever the sensor and a particular implementation results in. Require  the particular common receive implement a pre Ruuvi tag filter.

option5 . Let the process that acts on or displays or analysis the data include it's own algorithm to deal with possible anomalies that may be of interest.

**Comment by laurijamsa** [comment]
I just received a new Android user feedback about the same issue with the latest firmware. The CSV export reveals that broadcasts and GATT history humidity values differ by around 6,2%. User has no access to an iPhone.

"It is very welcome that the latest firmware allows you to synchronize historical data from tags. However, the app does not seem to correct for the calibration of the hygrometer, leading to very noisy charts." 

Find here screenshot and CSV export:

![image](https://user-images.githubusercontent.com/1311912/117571532-26d87f80-b0f9-11eb-9e98-c0b6c3832986.png)

[Guitar Case_20210509-0920.csv](https://github.com/ruuvi/ruuvi.firmware.c/files/6447454/Guitar.Case_20210509-0920.csv)

**Comment by ojousima** [comment]
Is this about applying the calibration constant to data?

**Comment by ojousima** [comment]
This was found to be Android issue in applying offset between logged / broadcasted data. Fixed in Android
