### ISSUE TITLE
Gaps in logged data

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#255]
Maybe a page which fails to get logged gets discarded? Potential solution, add a retry X times function?

![image](https://user-images.githubusercontent.com/2360368/117260882-32594b80-ae58-11eb-8a5e-9d3f1ca2bd78.png)

![image](https://user-images.githubusercontent.com/2360368/117260899-37b69600-ae58-11eb-9b50-70ebf93bf6cf.png)

**Comment by DG12** [comment]
Can you confirm the "missing" data by another means, for example influxdb?
Are the 2 images intended to show missing data on both android and IOS?

An aside: did you name one of your tags by its MAC address?

**Comment by ojousima** [comment]
Fixed in #256
