### ISSUE TITLE
3.30.2-debug: ARMGCC version prints partial test logs, doesn't print U64 timestamps. 

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#257]

**Comment by DG12** [comment]
Are you referring. to 
**"timestamp_ms": "ld",**

verses
"timestamp_ms": "41381",
when run via Segger Embedded Studio

**Comment by ojousima** [comment]
> Are you referring. to
> "timestamp_ms": "ld",

yes

**Comment by DG12** [comment]
It would seem the the ARMGCC toolchain version of printf does not handle %l  (ell)  ?

The difference is very nasty! Attempting to debug the ARMGCC version when SES uses different library.

Makes one wonder what other FUNCTIONAL differences there might be?

**Comment by ojousima** [comment]
> Makes one wonder what other FUNCTIONAL differences there might be?

Yes it does. The integration and system tests are done on ARMGCC binaries though

**Comment by ojousima** [comment]
Fixed in https://github.com/ruuvi/ruuvi.drivers.c/pull/221, thanks @DG12
