### ISSUE TITLE
v3.30.3+RC1: TMP117 consumes excessive power

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#266]
3.30.2 consumes 42 uA on B8+TMP117:
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/2360368/125964674-6eac846c-1c51-4278-9a86-ce40ca0ccfdf.png">

3.30.3+RC1 consumes 52 uA on B8+TMP117:
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/2360368/125965136-ac7351d3-7852-4d63-b2a0-ed338eea152a.png">

3.30.2 consumes 37 uA on B8
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/2360368/125966093-434ef06a-010d-4fd6-abd2-f8706fcebae3.png">

3.30.3+RC1 consumes 34 uA on B8
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/2360368/125965658-c26210e1-17c1-46df-aaee-9190e2831116.png">

It seems that TMP117 is not properly configured to not oversample in 3.30.3

**Comment by ojousima** [comment]
Found the reason, boards I have have too weak pull-ups to configure TMP at 400 kHz. Retesting with stronger resistors. Related to #262

**Comment by DG12** [comment]
Can you add which resistors were changed and from which value to which better value?

**Comment by ojousima** [comment]
> Can you add which resistors were changed and from which value to which better value?

RuuviTag B8 [published schematic](https://github.com/ruuvi/ruuvitag_hw/blob/master/ruuvitag_revb8/ruuvitag_revb8_schematic.pdf) has correct 1k value, our initial try was 4k7. No need to write old values down, as they weren't published just in case we'd need to tune them.

**Comment by DG12** [comment]
Surprised to see reset button removed.

**Comment by ojousima** [comment]
Fixed in #271
