### ISSUE TITLE
Pressure encoding overflow issue

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.firmware.c#280]
After pressure reaches 65534 (115534 Pa) and continues climbing, a variable overflows and encoding outputs wrong values.

Expected: Gap values under 50000 Pa to 50000 Pa and gap values over 115534 Pa to 115534 Pa.

Check also if other encoders (temperature, humidity, acceleration, battery voltage, tx power lack similar fixes.

**Comment by DG12** [comment]
highest was 1083.8mb = hPa (32.00 inHg) at Agata, Siberia, Russia (alt. 262m , 862ft) 

Perhaps there's something besides formatting that is muck

**Comment by ojousima** [comment]
Fixed in #https://github.com/ruuvi/ruuvi.endpoints.c/pull/35
