### ISSUE TITLE
Error in ruuviblog-branch

### ISSUE THREAD

**Issue by JZNT** [ruuvi/ruuvi.firmware.c#3]
Branch ruuviblog has an error in ./targets/ruuvitag_b/armgcc/package.sh line 18: 
`wget $BOOTLOADER`
Shouldn't it be 
`wget https://github.com/ruuvi/ruuvi.nrf5_sdk15_bootloader.c/releases/download/3.0.0/ $BOOTLOADER`

**Comment by ojousima** [comment]
Thanks, you're correct. I'll have it fixed in next release

**Comment by ojousima** [comment]
Fixed in 228f8b9, thanks.
