### ISSUE TITLE
flash routines use  boolean for "busy" flag should it be a counter - question

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#312]
Is it possible that multiple actions could be queued and the first one to complete calls event handler and incorrectly sets processing false even though there is still an outstanding action?

ruuvi.drivers.c/src/nrf5_sdk15_platform/flash/ruuvi_nrf5_sdk15_flash.c

delete: 
does a record find, sets processing  true, then does delete; then may set processing  false

set:
checks processing, does record find, sets processing true, then either does an update or write and sets processing false

get: 
checks processing, does record find, open, close

GC: 
checks processing, sets processing true, calls GC and exits.

fds_evt_handler 
sets  m_fds_processing  false when an event occurs.

**Comment by ojousima** [comment]
That's possible, access to flash busy flag should be protected by an atomic mutex.

Counter would not really help here, because only one part of program is supposed to access flash storage at a time, case where `busy` is two a bug has already occurred.

**Comment by DG12** [comment]
When you have a chance 
can you elaborate on "case where busy is two a bug has already occurred.'

Should this stay open?
