### ISSUE TITLE
Tag became "Not connectable" suddenly and rebooting the tag made it connectable again on iOS

### ISSUE THREAD

**Issue by priyonto** [ruuvi/ruuvi.firmware.c#326]
The tag was working fine until suddenly it stops showing it's connectable on the iOS app. The tag is on the latest firmware and when it was in "not connectable" mode the firmware update page showed something like this. 
![IMG_5133](https://user-images.githubusercontent.com/24395776/154104075-d743a55e-da66-4c49-980a-2261e1409af4.PNG)

I rebooted the iPhone, that did not fix the issue. But, rebooting the tag made it connectable instantly.

**Comment by ojousima** [comment]
I can reproduce this issue on one of my 3.31.1 tags, looking into how I can get a tag to lock up like this

**Comment by priyonto** [comment]
Thank you. :)

**Comment by ojousima** [comment]
I opened nRF Sniffer to scan BLE traffic and checked the sensor I have issue with. I forced a disconnect on sensor by doing NFC scan and observed that there is a device connecting to the sensor almost right away. 

Wireshark screen capture, you can see first device running a scan request and second connecting:
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/2360368/154292690-274d5099-fecf-4155-85c5-a3936aa82308.png">

I have no idea which device is connected to my tag, it might belong to someone in my household or my neighbor. I'd say this is not a firmware bug, but more of an user experience issue. It might be helpful to add a "Connect on NFC" feature where after NFC scan Ruuvi Station tries to immediately connect.

**Comment by priyonto** [comment]
Does it mean it connecting automatically to another device when NFC enabled device is around?

**Comment by DG12** [comment]
Can you take the sensor "out of range" of the unknown connector and see what happens? basement?

**Comment by ojousima** [comment]
> Does it mean it connecting automatically to another device when NFC enabled device is around?

The flow is: 
1) Tag is connected to unknown phone A
2) My phone B does NFC scan. Phone A disconnects
3) Phone A reconnects before I have a chance to connect with my phone B

 > Can you take the sensor "out of range" of the unknown connector and see what happens? basement?

Later this month, I'm currently quarantined.

**Comment by priyonto** [comment]
> The flow is:
> 
> 1. Tag is connected to unknown phone A
> 2. My phone B does NFC scan. Phone A disconnects
> 3. Phone A reconnects before I have a chance to connect with my phone B

This is super weird. I am wondering what is causing this behavior. This is not an app issue either, is it?

**Comment by ojousima** [comment]
> This is not an app issue either, is it?

Not really, some other device is "hijacking" the sensor connection. We could secure the connection by using out-of-band pairing, such as NFC but it has been a design decision to use open connections for simplicity
