### ISSUE TITLE
versioning lost major.minor.update

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#33]
NFC SW now reports 7 characters from GitHub.

Automatic versioning (only) by a tool looses the intelligence behind "This is a version".

I would like to suggest that SW "version" be returned to the traditional 3 numeric field format of major.minor.update.

Perhaps an additional field can be defined containing the GitHub ID ( and a date-time too!)

**Comment by DG12** [comment]
I personally prefer a compiled-on-date-time  which can be generated outside of a tool (like GitHub) and still be meaningful without access to the tool, similar to a simple include 
`uint32_t dateCompiled=0x39211512;
`
created by
`echo uint32_t dateCompiled=0x`date +%M%H%d%m\;` >dateCompiled.h # all numeric MMHHddmm
`

**Comment by ojousima** [comment]
The versioning tries to find major.minor.update from GitHub, if it is not available a commit hash is used instead. 

Compilation data isn't as informative, as the developer might have checked some older version and compiled it to test if some bug was already present there

**Comment by DG12** [comment]
Does "tries to find" mean that sometimes(?) there will be a  major.minor.update versions, like releases?

**Comment by ojousima** [comment]
Yes, this is the exact logic:
```
# Tag on this commit
TAG := $(shell git describe --tags --exact-match)
# Commit hash from git
COMMIT := $(shell git rev-parse --short HEAD)
VERSION := $(if $(TAG),\\\"$(TAG)\\\",\\\"$(COMMIT)\\\")
```
The `VERSION` gets then passed to compiler.

**Comment by DG12** [comment]
Perhaps including both in the NFC SW would be even better?

Does this make using git a requirement for development?

**Comment by ojousima** [comment]
Git is not required for developing, only the makefile building the packages requires git. Any firmware version can be passed to the compiler, including the compile time.

**Comment by DG12** [comment]
Version and Build as Apple Mac OS
<img width="206" alt="version-build" src="https://user-images.githubusercontent.com/2365961/71279720-7b723380-2327-11ea-85c2-89e73b6d9f08.png">

**Comment by ojousima** [comment]
Does this issue need some further discussion or work?

**Comment by DG12** [comment]
How do you feel about including both version and build to NFC SW ?

**Comment by ojousima** [comment]
Eventually the official builds are going to be pushed straight from Jenkins to GitHub Releases, so adding the build information isn't necessary from Ruuvi's point of view. Anyone is of course free to add additional information to their builds as they see fit.
