### ISSUE TITLE
SEN55 PM 2.5 Confirm set up, board connected to PC, data connection is working

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.firmware.c#338]
Description:

SEN55 PM 2.5 sensor, Confirm set up, board connected to PC, data connection is working

**Comment by TheSomeMan** [comment]
![image](https://github.com/ruuvi/ruuvi.firmware.c/assets/4346875/486929b8-231e-4956-a93c-cc60ad6d8d18)
