### ISSUE TITLE
Add support for Nordic SDK 17.2

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.firmware.c#90]

**Comment by ojousima** [comment]
Update might fix issue with NFC freezes: 
![image](https://user-images.githubusercontent.com/2360368/93497455-1cbf0200-f919-11ea-853f-a831905c3260.png)

**Comment by ojousima** [comment]
NFC binaries were back ported to SDK 15.3 in #153 , it's worth waiting a bit to see if issues with NFC are fixed

**Comment by ojousima** [comment]
NFC issues not detected anymore, maybe fixed?

**Comment by niksiboxi** [comment]
Unable to reproduce NFC crashing issue.

**Comment by DG12** [comment]
This issue is titled "Add support for Nordic SDK 17.2 " with a follow up regarding an NFC problem.

Is SDK 17.2 still a milestone ?
Should niksiboxi have closed this issue opened by Otso?
