### ISSUE TITLE
Logging measurements in advertise format would allow for storing much more data 

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#99]
in /app_log.h 
Would it be better to keep measurements in app_log_element_t in integer hundredths rather than float?
I wonder if there are sever compression considerations especially dealing with successive readings that are not represented well in hexadecimal fractions which are actually nearly the same.

Consider the value 0.10 which in floating point results in 0x3dcccccd. YUCK while in integer hundredths is simply 0x00...0A

Try using https://www.h-schmidt.net/FloatConverter/IEEE754.html on other simple measurements.

That is also more consistent with the transmission format.

**Comment by ojousima** [comment]
The goal is to add compression later on, current compression algorithm uses too much ram to decompress and compress data at the same time. This leads to need to flush current block to flash before starting decompression, which leads to oldest data being overwritten and leaves an under utilized block in flash.

**Comment by DG12** [comment]
Before adding compression, storing measurements in fixed point (just as in the transmission ) would require each element in the structure to take much less storage. Basically float point is best used when the range of possible values varies very greatly (i.e. orders of magnitude ). When the range is small floating point wastes 1 of 4 bytes for an exponent.

**Comment by ojousima** [comment]
Yes, I'd consider reducing the data type size to be a part of compression.

**Comment by ojousima** [comment]
Marked this as proposed enchantment. A good moment to work on this would be milestone 3.30.0 when acceleration logging is worked on. ref #24

**Comment by DG12** [comment]
Further reduction by storing timestamp in tenth of seconds and only using a 3 byte field allows range of up to 71 days. At 1 entry per second far this far exceeds the flash capacity. That is, if the RuuviTag is logging a sample every second and the log is circular and  the RuuviTag  must be recovered within 71 days.

Using the advertising format this would use the same number of bytes as float t,h,p and be able to  include t,h,p,x,y,z,move.

**Comment by ojousima** [comment]
Closing this as it will not be worked on near future.
